# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d95ad2ef3292b0108f8e610aac7cfc760221cba88a109539a082c2e52d37d46bf27b0e9f0096c8cf86a5606103f647602cc72335becc3a9e2d8db325bdb2edd0

test:
  secret_key_base: d23a285c7ddbcec95c5130016789a93a16e1c35c86c5568ebd19c7003fa7f6a7670042bcd7120fbf59664dba25efdfa483d24e5c7763236020d99f5d82ba5de2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8fe429c31dda921dd57295d74c7e4442a7880db4c72af41a77eb05b9f04f35175f6a6e28769c6c5de9e2183a9eb539af8af309881dfda227cf4e9e9726d9c1e3
